server:
  port: 8888


spring:
  cloud:
    consul:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
    gateway:
      mvc:
        routes:

          - id: rockbands
            uri: http://rockbandsservice:8080
            predicates:
              - Path=/api/rockbands/**
            filters:
              - RewritePath=/api/rockbands/?(?<segment>.*), /$\{segment}

          - id: swedishpuns
            uri: http://swedishpunsservice:8090
            predicates:
              - Path=/api/swedishpuns/**
            filters:
              - RewritePath=/api/swedishpuns/?(?<segment>.*), /$\{segment}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth:9000
